CREATE DATABASE IF NOT EXISTS nomosnow;
USE nomosnow;
CREATE TABLE IF NOT EXISTS products (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    barcode VARCHAR(255),
    description VARCHAR(MAX),
    status VARCHAR(10) NOT NULL
);
ALTER USER 'root' IDENTIFIED WITH mysql_native_password BY 'password';
FLUSH PRIVILEGES;